theme = "docuapi"
languageCode = "en-us"
baseurl = "https://gatewaysms.github.io/docs"
title = "DocuAPI Example Site"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true

defaultContentLanguage = "en"

[params]
search = true
  
# Configure the language example tabs.
#[[params.language_tabs]]
#key = "go"
#name = "Go"
[[params.language_tabs]]
key = "shell"
name = "Shell" 
#[[params.language_tabs]]
#key = "ruby"
#name = "Ruby"
#[[params.language_tabs]]
#key = "python"
#name = "Python"
#[[params.language_tabs]]
#key = "javascript"
#name = "Javascript"

#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "SMS Gateway Docs"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"<a href='http://sms-automatic-sending.appspot.com/'>Sign Up for a Developer Key</a>"
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true


[languages.nn]
languageName = "Nynorsk"
weight = 1
title = "DocuAPI-døme"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [
"<a href='#'>Registrer deg for ein utviklarnøkkel</a>",
"Dokumentasjonen er driven av [DocuAPI](https://github.com/bep/docuapi)",
"Hugo Theme av [bep](https://github.com/bep)"
]

[languages.nn.blackfriday]
# Norwegian uses angled quotes
angledQuotes = true
hrefTargetBlank = true